"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class BitExtent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    OFFSET_FIELD_NUMBER: builtins.int
    LENGTH_FIELD_NUMBER: builtins.int
    offset: builtins.int
    length: builtins.int
    def __init__(self,
        *,
        offset: builtins.int = ...,
        length: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["length",b"length","offset",b"offset"]) -> None: ...
global___BitExtent = BitExtent

class StreamInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DEFLATES_FIELD_NUMBER: builtins.int
    PUFFS_FIELD_NUMBER: builtins.int
    PUFF_LENGTH_FIELD_NUMBER: builtins.int
    @property
    def deflates(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BitExtent]: ...
    @property
    def puffs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BitExtent]: ...
    puff_length: builtins.int
    def __init__(self,
        *,
        deflates: typing.Optional[typing.Iterable[global___BitExtent]] = ...,
        puffs: typing.Optional[typing.Iterable[global___BitExtent]] = ...,
        puff_length: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["deflates",b"deflates","puff_length",b"puff_length","puffs",b"puffs"]) -> None: ...
global___StreamInfo = StreamInfo

class PatchHeader(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _PatchType:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _PatchTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[PatchHeader._PatchType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        BSDIFF: PatchHeader._PatchType.ValueType  # 0
        ZUCCHINI: PatchHeader._PatchType.ValueType  # 1
    class PatchType(_PatchType, metaclass=_PatchTypeEnumTypeWrapper):
        pass

    BSDIFF: PatchHeader.PatchType.ValueType  # 0
    ZUCCHINI: PatchHeader.PatchType.ValueType  # 1

    VERSION_FIELD_NUMBER: builtins.int
    SRC_FIELD_NUMBER: builtins.int
    DST_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    version: builtins.int
    @property
    def src(self) -> global___StreamInfo: ...
    @property
    def dst(self) -> global___StreamInfo:
        """The bsdiff patch is installed right after this protobuf."""
        pass
    type: global___PatchHeader.PatchType.ValueType
    def __init__(self,
        *,
        version: builtins.int = ...,
        src: typing.Optional[global___StreamInfo] = ...,
        dst: typing.Optional[global___StreamInfo] = ...,
        type: global___PatchHeader.PatchType.ValueType = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["dst",b"dst","src",b"src"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["dst",b"dst","src",b"src","type",b"type","version",b"version"]) -> None: ...
global___PatchHeader = PatchHeader
